version: '3'

services:
  app:
    build:
      context: docker/php73
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
    working_dir: "/var/www/sitell"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/sitell/public
      TZ: Asia/Tokyo

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./docker/my.conf:/etc/mysql/conf.d/my.conf
    environment:
      MYSQL_DATABASE: sitell
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
  
  test_db:
      image: mysql:5.7
      ports:
        - "3306"
      volumes:
        - ./docker/my.conf:/etc/mysql/conf.d/my.conf
      environment:
        MYSQL_DATABASE: sitell
        MYSQL_ROOT_PASSWORD: root
        TZ: Asia/Tokyo
